spring:
  application:
    name: service-client
  autoconfigure:
    exclude: org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration

  kafka:
    producer:
      valueSerializer: com.gupaoedu.service.client.kafka.ObjectSerializer
    consumer:
      groupId: gupao-group
      valueDeserializer: com.gupaoedu.service.client.kafka.ObjectDeserializer

  cloud:
    stream:
      bindings:
        person-source:
          destination: gupao
        person-sink:
          destination: gupao
          group: gupao-group

server:
  port: 9090 #随机端口